---
- name: Ansible Demo
  hosts: linuxservers 
  become: true

  tasks:
    - name: Stop nginx
      service:
        name: nginx
        state: stopped
    
    - name: Remove nginx latest version
      apt:
        name: nginx
        state: absent

    
